import './globals.css'
import TwoDimensionalPlot from './components/TwoDimensionalPlot/TwoDimensionalPlot'
import ClientOnly from './components/ClientOnly'



export const metadata = {
  title: 'Plotting plots in a probabily very dumb ways',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
      <ClientOnly>
        <TwoDimensionalPlot/>
      </ClientOnly>
      </body>
    </html>
  )
}
